/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAKIB
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        cutomer.setBackground(new Color(0,0,0,70));
        
         
    }
     
    String cs;
    String tid;
    
    
    public void ctablename(String b,String c){
      cs=b;
      tid=c;
      tName.setText(c);
  
    }
    
    
    public void showData(){
      try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            ResultSet rs=null;
            ResultSetMetaData rsm=null;
            PreparedStatement pstmt=con.prepareStatement("SELECT p_id,p_name,Quantuty,price FROM "+cs+"");
            rs=pstmt.executeQuery();
            rsm=rs.getMetaData();
            DefaultTableModel dtm=new  DefaultTableModel();
            Object[]columnNames=new Object[rsm.getColumnCount()];
            for(int i=0;i<rsm.getColumnCount();i++){
                columnNames[i]=rsm.getColumnLabel(i+1);
               dtm.addColumn(columnNames[i]);

            }
            
            while(rs.next()){
             Object[]data=new Object [rsm.getColumnCount()];
             for(int i=0;i<data.length;i++){
                 data[i]=rs.getObject(i+1);
             }
              dtm.addRow(data);
                 
                 
            }
             
          cutomer.setModel(dtm);
             
      
      }catch(Exception e){
          e.printStackTrace();
      }
      
      showData1();
     }
    
    public void showData1(){
      try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            ResultSet rs=null;
            ResultSetMetaData rsm=null;
            PreparedStatement pstmt=con.prepareStatement("SELECT t_id,total,date,sales_by FROM transaction WHERE t_id=?");
            pstmt.setString(1, tid);
            rs=pstmt.executeQuery();
            rsm=rs.getMetaData();
            DefaultTableModel dtm=new  DefaultTableModel();
            Object[]columnNames=new Object[rsm.getColumnCount()];
            for(int i=0;i<rsm.getColumnCount();i++){
                columnNames[i]=rsm.getColumnLabel(i+1);
               dtm.addColumn(columnNames[i]);

            }
            
            while(rs.next()){
             Object[]data=new Object [rsm.getColumnCount()];
             for(int i=0;i<data.length;i++){
                 data[i]=rs.getObject(i+1);
             }
              dtm.addRow(data);
                 
                 
            }
             
         tVeiw.setModel(dtm);
             
      
      }catch(Exception e){
          e.printStackTrace();
      }
     }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cutomer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tVeiw = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tName = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tVeiw1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selling Items");

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        cutomer.setBackground(new java.awt.Color(51, 51, 255));
        cutomer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        cutomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cutomer.setForeground(new java.awt.Color(240, 240, 240));
        cutomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "P_Id", "P_Name", "Quantity", "Price"
            }
        ));
        cutomer.setToolTipText("");
        cutomer.setGridColor(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(cutomer);

        tVeiw.setBackground(new java.awt.Color(255, 0, 0));
        tVeiw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tVeiw.setForeground(new java.awt.Color(240, 240, 240));
        tVeiw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tVeiw);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaction Id:");

        tName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tName.setForeground(new java.awt.Color(240, 240, 240));
        tName.setText("yu");

        tVeiw1.setBackground(new java.awt.Color(255, 0, 0));
        tVeiw1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tVeiw1.setForeground(new java.awt.Color(240, 240, 240));
        tVeiw1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tVeiw1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cutomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel tName;
    private javax.swing.JTable tVeiw;
    private javax.swing.JTable tVeiw1;
    // End of variables declaration//GEN-END:variables
}
