/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rakibul
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        currentTime();
    }
  String time;
     public void currentTime(){
         Thread clock =new Thread(){
          public void run(){
              for(;;){
                  time=""+new java.util.Date();
                  y.setText(time);
                  
                  try {
                      sleep(40);
                  } catch (InterruptedException ex) {
                      Logger.getLogger(Admin_Pannel.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
          }  
            };
         clock.start();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        show = new javax.swing.JCheckBox();
        y = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMANAGER = new javax.swing.JButton();
        tfUser1 = new javax.swing.JTextField();
        tfPass1 = new javax.swing.JPasswordField();
        show1 = new javax.swing.JCheckBox();
        y1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Saesllogin = new javax.swing.JButton();
        tfUser2 = new javax.swing.JTextField();
        tfPass2 = new javax.swing.JPasswordField();
        show2 = new javax.swing.JCheckBox();
        y2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Shop Login");
        setBounds(new java.awt.Rectangle(330, 50, 0, 0));
        setMinimumSize(new java.awt.Dimension(526, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(204, 0, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(204, 0, 51));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(120, 160));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("User Name:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 70, 80, 30);

        tfUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tfUser);
        tfUser.setBounds(200, 70, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 130, 80, 17);

        tfPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(tfPass);
        tfPass.setBounds(200, 130, 200, 30);

        show.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        show.setForeground(new java.awt.Color(240, 240, 240));
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel1.add(show);
        show.setBounds(420, 140, 110, 23);

        y.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        y.setForeground(new java.awt.Color(240, 240, 240));
        y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(y);
        y.setBounds(200, 224, 180, 20);

        btnLogin.setBackground(new java.awt.Color(0, 0, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(240, 240, 240));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(240, 180, 71, 30);

        jLabel4.setBackground(new java.awt.Color(153, 204, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Administrator Pannel");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 30, 210, 20);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/1.jpg"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(10, 10, 490, 240);

        jTabbedPane1.addTab("Administrator", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Manager Login Pannel");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(160, 30, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Manager Id:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 90, 90, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Password:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 130, 100, 17);

        btnMANAGER.setBackground(new java.awt.Color(0, 255, 0));
        btnMANAGER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMANAGER.setText("Login");
        btnMANAGER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMANAGERActionPerformed(evt);
            }
        });
        jPanel2.add(btnMANAGER);
        btnMANAGER.setBounds(240, 180, 90, 30);

        tfUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUser1ActionPerformed(evt);
            }
        });
        jPanel2.add(tfUser1);
        tfUser1.setBounds(200, 80, 190, 30);
        jPanel2.add(tfPass1);
        tfPass1.setBounds(200, 130, 190, 30);

        show1.setText("Show");
        show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show1ActionPerformed(evt);
            }
        });
        jPanel2.add(show1);
        show1.setBounds(400, 140, 120, 23);

        y1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        y1.setForeground(new java.awt.Color(240, 240, 240));
        y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(y1);
        y1.setBounds(200, 224, 180, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/2.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 10, 490, 240);

        jTabbedPane1.addTab("Manager", jPanel2);

        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Sales Login Pannel");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(170, 40, 200, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Sales ID:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(110, 90, 70, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Password:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(110, 130, 90, 30);

        Saesllogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Saesllogin.setText("login");
        Saesllogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaeslloginActionPerformed(evt);
            }
        });
        jPanel3.add(Saesllogin);
        Saesllogin.setBounds(230, 180, 70, 30);
        jPanel3.add(tfUser2);
        tfUser2.setBounds(190, 90, 170, 30);
        jPanel3.add(tfPass2);
        tfPass2.setBounds(190, 130, 170, 30);

        show2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        show2.setText("Show");
        show2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show2ActionPerformed(evt);
            }
        });
        jPanel3.add(show2);
        show2.setBounds(370, 140, 100, 23);

        y2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        y2.setForeground(new java.awt.Color(240, 240, 240));
        y2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(y2);
        y2.setBounds(200, 224, 180, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/8.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 510, 270);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("My_Bank Vresion 0.1");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 230, 180, 14);

        jTabbedPane1.addTab("Sales", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(6, 130, 510, 284);

        jToolBar1.setBackground(new java.awt.Color(204, 255, 204));
        jToolBar1.setRollover(true);

        jButton1.setText("Print");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 516, 0);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/eshop2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(4, 4, 510, 150);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void show2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show2ActionPerformed
        // TODO add your handling code here:
        if(show2.isSelected()){
            tfPass2.setEchoChar((char) 0);
        }else{
            tfPass2.setEchoChar('*');
        }

    }//GEN-LAST:event_show2ActionPerformed

    private void SaeslloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaeslloginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM sales_man WHERE em_id=? AND password=?");
            pstmt.setString(1, tfUser2.getText());
            pstmt.setString(2, tfPass2.getText());
            ResultSet rs=pstmt.executeQuery();

            if(rs.next()){
                String name=rs.getString("em_name");
                JOptionPane.showMessageDialog(null, "Welcome "+name);

                Sales s=new Sales();
                s.setVisible(true);
                s.wel(name);
                dispose();
            }else{

                JOptionPane.showMessageDialog(null, "Invalid User Name or Password","Login Failed",JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_SaeslloginActionPerformed

    private void show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show1ActionPerformed
        // TODO add your handling code here:

        if(show1.isSelected()){
            tfPass1.setEchoChar((char) 0);
        }else{
            tfPass1.setEchoChar('*');
        }
    }//GEN-LAST:event_show1ActionPerformed

    private void tfUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUser1ActionPerformed

    private void btnMANAGERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMANAGERActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM employee WHERE em_id=? AND password=?");
            pstmt.setString(1, tfUser1.getText());
            pstmt.setString(2, tfPass1.getText());
            ResultSet rs=pstmt.executeQuery();

            if(rs.next()){
                String name=rs.getString("em_name");
                JOptionPane.showMessageDialog(null, "Welcome "+name);

                Manager_pannel ad=new Manager_pannel();
                ad.setVisible(true);
                ad.wel(name);
                dispose();
            }else{

                JOptionPane.showMessageDialog(null, "Invalid User Name or Password","Login Failed",JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnMANAGERActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM admin WHERE user=? AND pass=?");
            pstmt.setString(1, tfUser.getText());
            pstmt.setString(2, tfPass.getText());
            ResultSet rs=pstmt.executeQuery();

            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome");
                Admin_Pannel ad=new Admin_Pannel();
                ad.setVisible(true);
                dispose();
            }else{

                JOptionPane.showMessageDialog(null, "Invalid User Name or Password","Login Failed",JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        if(show.isSelected()){
            tfPass.setEchoChar((char) 0);
        }else{
            tfPass.setEchoChar('*');
        }

    }//GEN-LAST:event_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        splash Splash=new splash();
    start Start=new start();
    Splash.setVisible(true);
    int i=0;
        try {
            for(i=0;i<=100;i=i+2){
            Thread.sleep(40);
             Splash.loadingnum.setText(Integer.toString(i)+"%");
             Splash.loadingbar.setValue(i);
             if(i==100){
                Splash.setVisible(false);
               
             }
            }
        } catch (Exception e) {
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Saesllogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMANAGER;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox show;
    private javax.swing.JCheckBox show1;
    private javax.swing.JCheckBox show2;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JPasswordField tfPass1;
    private javax.swing.JPasswordField tfPass2;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUser1;
    private javax.swing.JTextField tfUser2;
    private javax.swing.JLabel y;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    // End of variables declaration//GEN-END:variables
}
