/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rakibul
 */
public class Manage_product extends javax.swing.JFrame {

    /**
     * Creates new form Manage_product
     */
    public Manage_product() {
        initComponents();
        ddproduct.addItem("Select Id");
        add();
    }
    
     String n="";
    public void name(String b){
        tfWel.setText("Welcome "+b);
        n=b;
    }
    public void add(){
         try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
           PreparedStatement pstmt=con.prepareStatement("SELECT * FROM product");
           ResultSet rs=pstmt.executeQuery();
           
           while(rs.next()){
                
               String id=rs.getString("p_id");
        
               ddproduct.addItem(id);
               
           }
            
           

            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfWel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ddproduct = new javax.swing.JComboBox<>();
        tfName = new javax.swing.JTextField();
        tfPurchase = new javax.swing.JTextField();
        tfSales = new javax.swing.JTextField();
        tfStock = new javax.swing.JTextField();
        tfUpdate = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfPhoto = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage_Product");
        setBounds(new java.awt.Rectangle(350, 5, 0, 0));
        setMinimumSize(new java.awt.Dimension(580, 480));
        setPreferredSize(new java.awt.Dimension(580, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        tfWel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfWel.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(tfWel);
        tfWel.setBounds(20, 20, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Manage Product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 50, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product_Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Purchase price:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 110, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 370, 50, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 50, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Last_upadte_by:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 130, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 130, 50, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Stock:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 44, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Sales Price:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 230, 90, 17);

        ddproduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddproductItemStateChanged(evt);
            }
        });
        ddproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddproductMouseClicked(evt);
            }
        });
        ddproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddproductActionPerformed(evt);
            }
        });
        getContentPane().add(ddproduct);
        ddproduct.setBounds(140, 90, 210, 30);

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName);
        tfName.setBounds(140, 130, 210, 30);
        getContentPane().add(tfPurchase);
        tfPurchase.setBounds(140, 180, 210, 30);
        getContentPane().add(tfSales);
        tfSales.setBounds(140, 220, 210, 30);
        getContentPane().add(tfStock);
        tfStock.setBounds(140, 270, 210, 30);
        getContentPane().add(tfUpdate);
        tfUpdate.setBounds(140, 310, 210, 30);
        getContentPane().add(tfDate);
        tfDate.setBounds(140, 360, 210, 30);

        tfPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tfPhoto);
        tfPhoto.setBounds(360, 160, 200, 210);

        btnUpdate.setBackground(new java.awt.Color(0, 0, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(240, 240, 240));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(373, 90, 80, 30);

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(240, 240, 240));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(470, 90, 80, 30);

        image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/11.png"))); // NOI18N
        getContentPane().add(image);
        image.setBounds(-10, 0, 590, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ddproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddproductActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void ddproductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddproductItemStateChanged
        // TODO add your handling code here:
       
         try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
           PreparedStatement pstmt=con.prepareStatement("SELECT * FROM product WHERE p_id=?");
           String id=ddproduct.getSelectedItem().toString();
           pstmt.setString(1, id);
           ResultSet rs=pstmt.executeQuery();
           if(rs.next()){
               String name=rs.getString("p_name");
               tfName.setText(name);
               int pp=rs.getInt("purchase_price");
               tfPurchase.setText(String.valueOf(pp));
               
               int sp=rs.getInt("salce_price");
               tfSales.setText(String.valueOf(sp));
               
               int st=rs.getInt("stock");
               tfStock.setText(String.valueOf(st));
               String up=rs.getString("upadate_by");
               tfUpdate.setText(up);
              
               Date jd=rs.getDate("date");
                tfDate.setText(String.valueOf(jd));
               
                byte[] ima=rs.getBytes("photo");
                Image imag=Toolkit.getDefaultToolkit().createImage(ima);
                ImageIcon icon=new ImageIcon(imag);
                tfPhoto.setIcon(icon);
                
               
           }else{
               tfName.setText("");
                tfPurchase.setText(""); 
                tfSales.setText("");
                 tfStock.setText("");
                  tfUpdate.setText("");
                   tfDate.setText("");
                   String s5="";
                 s5 = "C:\\Users\\rakibul\\Documents\\NetBeansProjects\\My_Bank\\Image\\2.jpg";
      
                 tfPhoto.setIcon(new ImageIcon(s5));
                
           }
          
            
           

            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ddproductItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
          PreparedStatement pstmt=con.prepareStatement("UPDATE product SET p_name=?,purchase_price=?,salce_price=?,stock=?,upadate_by=?,date=NOW() WHERE p_id=?");
           
         pstmt.setString(1, tfName.getText());
         String pprice=tfPurchase.getText();
         int pp=Integer.parseInt(pprice);
         pstmt.setInt(2, pp);
         
         String sprice=tfSales.getText();
         int sp=Integer.parseInt(sprice);
         pstmt.setInt(3, sp);
         
         String stock=tfStock.getText();
         int st=Integer.parseInt(stock);
         pstmt.setInt(4, st);
       
         pstmt.setString(5, n);
         String id=ddproduct.getSelectedItem().toString();
         pstmt.setString(6, id);
         
         int i=pstmt.executeUpdate();
         
         if(i>0){
             JOptionPane.showMessageDialog(null, "Product Updated Successfully");
         }else{
             JOptionPane.showMessageDialog(null, "Failed");
         }
         
         
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         try{
          Class.forName("com.mysql.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
          PreparedStatement pstmt=con.prepareStatement("DELETE FROM product WHERE p_id=?");
           
       String id=ddproduct.getSelectedItem().toString();
         pstmt.setString(1,id);
         int i=pstmt.executeUpdate();
         if(i>0){
             
             JOptionPane.showMessageDialog(null, "Deleted Success");
             this.setVisible(true);
            
         }
         
         
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
 
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ddproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddproductMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_ddproductMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> ddproduct;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfName;
    private javax.swing.JLabel tfPhoto;
    private javax.swing.JTextField tfPurchase;
    private javax.swing.JTextField tfSales;
    private javax.swing.JTextField tfStock;
    private javax.swing.JTextField tfUpdate;
    private javax.swing.JLabel tfWel;
    // End of variables declaration//GEN-END:variables
}
