/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import static com.exam.Admin_Pannel.rpass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAKIB
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        add();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tt1 = new javax.swing.JTable();
        dateselect1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        td = new javax.swing.JLabel();
        btnRef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daily Transaction");

        jPanel1.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnView.setBackground(new java.awt.Color(255, 51, 51));
        btnView.setText("Go");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 50, 30));

        tt1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        tt1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt1.setForeground(new java.awt.Color(0, 0, 255));
        tt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Title 3", "Title 4"
            }
        ));
        tt1.setSelectionBackground(new java.awt.Color(240, 240, 240));
        tt1.setSelectionForeground(new java.awt.Color(0, 0, 204));
        jScrollPane1.setViewportView(tt1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1410, 640));
        jPanel1.add(dateselect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 200, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Select Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, -1));

        td.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        td.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 230, 30));

        btnRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/exam/refresh.png"))); // NOI18N
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });
        jPanel1.add(btnRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        showData();

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
     add();
    }//GEN-LAST:event_btnRefActionPerformed
    public void showData() {
        try {

            java.util.Date d1 = dateselect1.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dt = df.format(d1);
            java.util.Date utild = df.parse(dt);
            java.sql.Date sqlD = new java.sql.Date(new java.util.Date(utild.getTime()).getTime());

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank", "root", Admin_Pannel.rpass);
            ResultSet rs = null;
            ResultSetMetaData rsm = null;
            PreparedStatement pstmt = con.prepareStatement("SELECT p_id,p_name,price,Quantuty,p_total,sales_by,date FROM billing WHERE date=?");
            pstmt.setDate(1, sqlD);
            rs = pstmt.executeQuery();
            rsm = rs.getMetaData();
            DefaultTableModel dtm = new DefaultTableModel();
            Object[] columnNames = new Object[rsm.getColumnCount()];
            for (int i = 0; i < rsm.getColumnCount(); i++) {
                columnNames[i] = rsm.getColumnLabel(i + 1);
                dtm.addColumn(columnNames[i]);

            }
              int c=0;
            while (rs.next()) {
                Object[] data = new Object[rsm.getColumnCount()];
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getObject(i + 1);
                    c++;
                }
                dtm.addRow(data);

            }
            
             td.setText(String.valueOf(sqlD));
            tt1.setModel(dtm);
            if(c<1){
                JOptionPane.showMessageDialog(null, "No Transaction Found","Alert",JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    String yu;
    String du;
    String mu;

    public void currentDate() {

        Calendar cal = new GregorianCalendar();
        int yy = cal.get(Calendar.YEAR);
        int m = cal.get(Calendar.MONTH);
        int d = cal.get(Calendar.DATE);

        du = String.valueOf(d);

        yu = String.valueOf(yy);

        String[] month = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};

        mu = month[m];

    }

    int total1 = 0;

    public void add() {

        currentDate();
        try {
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank", "root", Admin_Pannel.rpass);
            ResultSet rs = null;
            ResultSetMetaData rsm = null;
            PreparedStatement pstmt = con.prepareStatement("SELECT p_id,p_name,Quantuty,price,p_total,sales_by,date FROM billing WHERE date=?");
            pstmt.setDate(1, new java.sql.Date(new java.util.Date("" + du + "-" + mu + "-" + yu + "").getTime()));
            rs = pstmt.executeQuery();
            rsm = rs.getMetaData();
            DefaultTableModel dtm = new DefaultTableModel();
            Object[] columnNames = new Object[rsm.getColumnCount()];
            for (int i = 0; i < rsm.getColumnCount(); i++) {
                columnNames[i] = rsm.getColumnLabel(i + 1);
                dtm.addColumn(columnNames[i]);

            }

            while (rs.next()) {
                Object[] data = new Object[rsm.getColumnCount()];
                for (int i = 0; i < data.length; i++) {
                    data[i] = rs.getObject(i + 1);
                }
                dtm.addRow(data);

            }
              td.setText("Today's Information:");
            tt1.setModel(dtm);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRef;
    private javax.swing.JButton btnView;
    private com.toedter.calendar.JDateChooser dateselect1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel td;
    private javax.swing.JTable tt1;
    // End of variables declaration//GEN-END:variables
}
