/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.exam;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAKIB
 */
public class transaction_all extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public transaction_all() {
        initComponents();
        cutomer.setBackground(new Color(0,0,0,70));
        
         
    }
     
    String cs;
    String sc;
    
    
    public void ctablename(String b){
      cs="s"+b;
      sc=b;
     
     tid.setText(b);
    }
    
    
    public void showData(){
      try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            ResultSet rs=null;
            ResultSetMetaData rsm=null;
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM "+cs+"");
            rs=pstmt.executeQuery();
            rsm=rs.getMetaData();
            DefaultTableModel dtm=new  DefaultTableModel();
            Object[]columnNames=new Object[rsm.getColumnCount()];
            for(int i=0;i<rsm.getColumnCount();i++){
                columnNames[i]=rsm.getColumnLabel(i+1);
               dtm.addColumn(columnNames[i]);

            }
            
            while(rs.next()){
             Object[]data=new Object [rsm.getColumnCount()];
             for(int i=0;i<data.length;i++){
                 data[i]=rs.getObject(i+1);
             }
              dtm.addRow(data);
                 
                 
            }
             
          cutomer.setModel(dtm);
             
      
      }catch(Exception e){
          e.printStackTrace();
      }
     }
    
    public void showTotal(){
      try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_bank","root",Admin_Pannel.rpass);
            ResultSet rs=null;
            ResultSetMetaData rsm=null;
            PreparedStatement pstmt=con.prepareStatement("SELECT * FROM transaction WHERE t_id="+sc+"");
            rs=pstmt.executeQuery();
            rsm=rs.getMetaData();
            DefaultTableModel dtm=new  DefaultTableModel();
            Object[]columnNames=new Object[rsm.getColumnCount()];
            for(int i=0;i<rsm.getColumnCount();i++){
                columnNames[i]=rsm.getColumnLabel(i+1);
               dtm.addColumn(columnNames[i]);

            }
            
            while(rs.next()){
             Object[]data=new Object [rsm.getColumnCount()];
             for(int i=0;i<data.length;i++){
                 data[i]=rs.getObject(i+1);
             }
              dtm.addRow(data);
                 
                 
            }
             
          taTotal.setModel(dtm);
             
      
      }catch(Exception e){
          e.printStackTrace();
      }
     }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cutomer = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taTotal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selling Items");
        setMinimumSize(new java.awt.Dimension(840, 490));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        cutomer.setBackground(new java.awt.Color(51, 51, 255));
        cutomer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        cutomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cutomer.setForeground(new java.awt.Color(240, 240, 240));
        cutomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P_Id", "P_Name", "Quantity", "Price", "Cost"
            }
        ));
        cutomer.setToolTipText("");
        cutomer.setGridColor(new java.awt.Color(0, 102, 204));
        jScrollPane1.setViewportView(cutomer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 40, 840, 350);

        taTotal.setBackground(new java.awt.Color(255, 0, 0));
        taTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        taTotal.setForeground(new java.awt.Color(240, 240, 240));
        taTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Transaction_id", "Total", "Sold_By", "Cost", "date"
            }
        ));
        jScrollPane2.setViewportView(taTotal);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 390, 840, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Transaction Id:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 10, 100, 20);

        tid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tid.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(tid);
        tid.setBounds(400, 10, 280, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 840, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction_all().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cutomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable taTotal;
    private javax.swing.JLabel tid;
    // End of variables declaration//GEN-END:variables
}
